# Task Name: (Required) 
task_name: 'InfraScan'
# Task Author: (Required) 
author: 'InfraScan'
# Task Description: (Optional when using markdown) 
description: 'Task description'
# Task Description Markdown ##
markdownDescriptionPath: './README.md'
# Repository URL: (Required)
repositoryUrl: 'https://github.com/InfraScanApp/InfraScan' 
# Image URL: (Required) Will be displayed in desktop node
imageUrl: 'https://i.imgur.com/EgiR8Yt.png'
# Info URL: (Required) Will be displayed in desktop node
infoUrl: 'https://infrascan.app/'

# Task executable network: (Required | DEVELOPMENT, ARWEAVE, or IPFS) : IPFS is the default and common value
task_executable_network: 'IPFS'

# Task audit program: (Required) IPFS: Path to your executable | DEVELOPMENT: Leave it as 'main'
task_audit_program: 'dist/main.js'

# Round time: (Required) Duration of task, measured in slots (with each slot approximately equal to 408ms).
# 1 hour = 3600 seconds = 3,600,000ms ÷ 408ms per slot = 8823.529 slots
round_time: 8823.529

# Audit window: (Required) The audit window should be greater than 1/3 of the round time.
# OPTIMIZED: Increased from 18 to 25 minutes for better global node support
audit_window: 3676      # ~25 minutes (8823.529 × 0.42) - More time for global nodes

# Submission window: (Required) The submission window should be greater than 1/3 of the round time.
# OPTIMIZED: Increased from 20 to 22 minutes for better reliability
submission_window: 3236  # ~22 minutes (8823.529 × 0.37) - More time for network delays

# Minimum stake amount: (Required) The minimum amount of KOII that a user must stake in order to participate in the task.
minimum_stake_amount: 0.1

# Task Bounty Type: (Required | KOII or KPL) 
task_type: 'KPL'

# Token Mint Address: (ONLY task_type == KPL) Fire Token as an example here. 
token_type: "DSWQ7twRXgv6p3rbpECpXuPRKFR884zvDAebS8uNKG4z"

# Total bounty amount:  (Required) The total bounty amount that will be distributed to the task. (Not accepted in case of update task).
total_bounty_amount: 25920  # PRODUCTION: 30 days with 30 nodes (2,160 tokens/day × 12 days = 25,920)

# Bounty amount per round: (Required) Maximum distribution per round (safety limit only)
# Actual distribution is dynamic: 3 tokens × number of approved nodes
# This value prevents runaway costs if too many nodes join suddenly
bounty_amount_per_round: 90  # PRODUCTION: Safety limit for 30 nodes max (90 ÷ 3 = 30 nodes)

# Allowed failed distributions: (Required) Number of times re-submission is allowed for the distribution list in case of an audit, it is also the rounds of submission it will keep. 
allowed_failed_distributions: 3

# Space: (Required) Expected Task Data Size in MBs for the account size. 
# Minimum: 1 for production, 0.1 for testing; Calculation Details: https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#space
space: 1

# Requirement Tags: (Optional): To add more global variables and task variables, please refer to the type, value, description format shown below.
requirementsTags: []
  
# Tags: You can select the tags here via https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#tags
tags: ["Uptime", "Hardware", "Data Capture", "Probe"] 
# Environment: (Required | TEST or PRODUCTION) Production mode will expose your task to all the task runners. 
environment: "PRODUCTION"

#################################### BELOW IS FOR UPDATE TASK ONLY ####################################
# Old Task ID: (ONLY for task update) 
task_id: 'DUnxjkPv5bTvcj4ydvFWPyGB6ui99Lrg2MSpRqwC3sCv'

# Migration Description: (ONLY for task update)
migrationDescription: 'Production scaling: Updated bounty limits to support 30 nodes max at 3 tokens per round (90 tokens/round), increased total bounty for production deployment'
