# Task Name: (Required) 
task_name: 'InfraScan'
# Task Author: (Required) 
author: 'InfraScan'
# Task Description: (Optional when using markdown) 
description: 'Task description'
# Task Description Markdown ##
markdownDescriptionPath: './README.md'
# Repository URL: (Required)
repositoryUrl: 'https://github.com/InfraScanApp/InfraScan' 
# Image URL: (Required) Will be displayed in desktop node
imageUrl: 'https://i.imgur.com/EgiR8Yt.png'
# Info URL: (Required) Will be displayed in desktop node
infoUrl: 'https://infrascan.app/'

# Task executable network: (Required | DEVELOPMENT, ARWEAVE, or IPFS) : IPFS is the default and common value
task_executable_network: 'IPFS'

# Task audit program: (Required) IPFS: Path to your executable | DEVELOPMENT: Leave it as 'main'
task_audit_program: 'dist/main.js'

# Round time: (Required) Duration of task, measured in slots (with each slot approximately equal to 408ms).
# 57 minutes = 3420 seconds ÷ 0.408s = 8382.353 slots
round_time: 8382.353

# Audit window: (Required) The audit window should be greater than 1/3 of the round time. 
# OPTIMIZED: Increased to 40% for better audit and distribution processing
# 40% of round time = 3352.941 slots ≈ 23 minutes
audit_window: 3352.941      # ~23 minutes (8382.353 × 0.40) - Adequate time for audit + distribution

# Submission window: (Required) The submission window should be greater than 1/3 of the round time. 
# OPTIMIZED: Reduced to 45% to provide more buffer time
# 45% of round time = 3772.059 slots ≈ 26 minutes
submission_window: 3772.059  # ~26 minutes (8382.353 × 0.45) - Sufficient time for global submissions

# Minimum stake amount: (Required) The minimum amount of ISCAN that a user must stake in order to participate in the task.
minimum_stake_amount: 1

# Task Bounty Type: (Required | KOII or KPL) 
task_type: 'KPL'

# Token Mint Address: (ONLY task_type == KPL) Fire Token as an example here. 
token_type: "DSWQ7twRXgv6p3rbpECpXuPRKFR884zvDAebS8uNKG4z"

# Total bounty amount:  (Required) The total bounty amount that will be distributed to the task. (Not accepted in case of update task).
total_bounty_amount: 1000000  # PRODUCTION: Initial bounty - will be monitored and topped up as needed

# Bounty amount per round: (Required) Maximum distribution per round (safety limit only)
# Actual distribution is dynamic: 3 tokens × number of approved nodes
# This value prevents runaway costs if too many nodes join suddenly
bounty_amount_per_round: 4000  # PRODUCTION: Safety limit for 1333 nodes max (4000 ÷ 3 = 1333 nodes)

# Allowed failed distributions: (Required) Number of times re-submission is allowed for the distribution list in case of an audit, it is also the rounds of submission it will keep. 
allowed_failed_distributions: 3

# Space: (Required) Expected Task Data Size in MBs for the account size. 
# Minimum: 1 for production, 0.1 for testing; Calculation Details: https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#space
space: 1

# Requirement Tags: (Optional): To add more global variables and task variables, please refer to the type, value, description format shown below.
requirementsTags: []
  
# Tags: You can select the tags here via https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#tags
tags: ["Uptime", "Hardware", "Data Capture", "Probe"] 
# Environment: (Required | TEST or PRODUCTION) Production mode will expose your task to all the task runners. 
environment: "PRODUCTION"

#################################### BELOW IS FOR UPDATE TASK ONLY ####################################
# Old Task ID: (ONLY for task update) 
task_id: '8Pps7WLrtiUjhhjNai8baWo33NNL7S3kSJLTqxjsH7UT'

# Migration Description: (ONLY for task update)
migrationDescription: 'FLEXIBLE BOUNTY: Updated to 1M initial bounty with 4000 tokens per round limit. Total bounty will be monitored and topped up as needed for community growth.'
